# PyBOMBS

FROM p4g

# Add recipes to PyBOMBS
RUN pybombs recipes add p4g-toys git+https://github.com/jschiefer/p4g-toys.git
RUN pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
RUN pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
